sudo: false
language: python

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6

dist: trusty

branches:
  only:
  - master

notifications:
    email: true

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get update;
    fi;
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    else
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    fi;
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export CONDA_BLD_PATH="$HOME/conda-bld"
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - if [[ "$BRANCH" == "master" ]]; then
      export CONDA_BUILD_ARGS_EXTRA="";
    else
      export CONDA_BUILD_ARGS_EXTRA="--no-anaconda-upload";
    fi;
  - pip install --upgrade pip
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload yes
  - conda config --add channels menpo
  - conda update -q conda
  - conda info -a
  - conda install -q -y pip requests conda-build anaconda-client
  - conda create -q -n test-build-environment python=$TRAVIS_PYTHON_VERSION
  - conda install -q -y -c menpo opencv3
  - export PYTHON="$TRAVIS_PYTHON_VERSION"
  - source activate test-build-environment
  - export PYBOT_CONDA_BLD_OUTPUT="$(conda build tools/conda.recipe --output)"
  - conda build tools/conda.recipe --python $TRAVIS_PYTHON_VERSION $CONDA_BUILD_ARGS_EXTRA
  - conda convert -p osx-64 -o $CONDA_BLD_PATH $PYBOT_CONDA_BLD_OUTPUT
  - conda install -q -y pybot --use-local

after_success:
 - if [[ "$BRANCH" == "master" ]]; then
      anaconda -v -t $ANACONDA_API_TOKEN upload -u $ANACONDA_USER --force $CONDA_BLD_PATH/osx-64/*.tar.bz2;
   fi;

script:
  - python -c 'import pybot'
