package:
    name: pybot
    version: 0.2

source:
    git_url: https://github.com/spillai/pybot.git
    git_branch: master

build:
  number: 1

requirements:
    build:
        - cmake
        - numpy
        - pip
        - wheel
        - opencv3
        - eigen
        - gflags
        - glog
        - boost
    run:
        - numpy
        - scipy
        - protobuf
        - pyzmq
        - opencv3
        - eigen
        - matplotlib
        - pytables
        - pandas

    test:
      imports:
        - pybot
        - pybot.vision
        - pybot.utils
        - pybot.geometry
        - pybot.externals

    commands:
        - python -c "import pybot.vision; import pybot.utils; import
          pybot.externals; import pybot.geometry;"

about:
    license: MIT
    summary: Research tools for autonomous systems using Python
